# This checks if each column have the correct data type
COLUMNS:
  fixed_acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: float64
  chlorides: float64
  free sulfur: float64
  total sulfur: float64
  density: float64
  pH: float64
  sulphates: float64
  alcohol: float64
  quality: int64

  TARGET_COLUMN:
    name: quality